name: Continuous Build FreeBSD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags-ignore:
      - '*.*'
    paths:
      - 'src/**'
      - '!src/linux/**'
      - '!src/osx/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/continuous-build-freebsd.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '!src/linux/**'
      - '!src/osx/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/continuous-build-freebsd.yml'

jobs:
  build-freebsd:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        uses: vmactions/freebsd-vm@v0
        with:
          release: 13.1
          usesh: true
          prepare: |
            pkg install -y gmake gcc11 coreutils git
            git config --global --add safe.directory /Users/runner/work/btop/btop
          run: |
            gmake
            GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
            mv bin/btop bin/btop-$GIT_HASH
            ls -alh bin
      - uses: actions/upload-artifact@v3
        with:
          name: btop-x86_64-FreeBSD-13.1
          path: 'bin/*'
      
