name: Continuous Build OpenBSD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags-ignore:
      - '*.*'
    paths:
      - 'src/**'
      - '!src/linux/**'
      - '!src/osx/**'
      - '!src/freebsd/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/continuous-build-openbsd.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '!src/linux/**'
      - '!src/osx/**'
      - '!src/freebsd/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/continuous-build-openbsd.yml'

jobs:
  build-openbsd:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile
        uses: vmactions/openbsd-vm@v1
        with:
          release: '7.4'
          usesh: true
          prepare: |
            pkg_add gmake gcc%11 g++%11 coreutils git lowdown
            git config --global --add safe.directory /home/runner/work/btop/btop
          run: |
            gmake CXX=eg++ STATIC=true STRIP=true
            GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
            mv bin/btop bin/btop-GCC11-"$GIT_HASH"
            ls -alh bin

      - uses: actions/upload-artifact@v3
        with:
          name: btop-x86_64-openbsd-7.4
          path: 'bin/*'
          if-no-files-found: error
