name: Continuous Build FreeBSD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags-ignore:
      - '*.*'
    paths:
      - 'src/**'
      - '!src/linux/**'
      - '!src/osx/**'
      - '!src/openbsd/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/continuous-build-freebsd.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '!src/linux/**'
      - '!src/osx/**'
      - '!src/openbsd/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/continuous-build-freebsd.yml'

jobs:
  build-freebsd:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    strategy:
      matrix:
        compiler: ["clang++", "g++"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile
        uses: vmactions/freebsd-vm@v1
        with:
          release: '14.0'
          usesh: true
          prepare: |
            pkg install -y gmake gcc coreutils git lowdown
            git config --global --add safe.directory /home/runner/work/btop/btop
          run: |
            CXX=${{ matrix.compiler }} gmake STATIC=true STRIP=true
            GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
            COMPILER=$(echo ${{ matrix.compiler }} | sed 's/clang++/llvm/' | sed 's/g++/gcc/')
            mv bin/btop bin/btop-"$COMPILER"-"$GIT_HASH"
            ls -alh bin

      - uses: actions/upload-artifact@v3
        with:
          name: btop-x86_64-freebsd-14
          path: 'bin/*'
          if-no-files-found: error
